# Generated by Django 4.1.4 on 2023-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('denomination', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('typ', models.CharField(max_length=200)),
                ('object', models.CharField(max_length=200)),
                ('lettre', models.CharField(max_length=500)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
