# Generated by Django 4.1.4 on 2023-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quartier_id', models.IntegerField()),
                ('img', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('localisation', models.CharField(max_length=100)),
                ('map_address', models.CharField(max_length=100)),
            ],
        ),
    ]
